
let mechanic = [
	token( "casual", "" ),
	token( "turn based" ),
	token( "real time" ),
	token( "leveling" ),
	token( "progression tree" ),
	token( "progression web" ),
	token( "unfolding gameplay", "an" ),
	token( "negociation" ),
	token( "gambling" ),
	token( "trading" ),
	token( "player customisation" ),
	token( "vehicle building" ),
	token( "procedural generation" ),
	token( "permadeath" ),
	token( "prestige" ),
	token( "branching story" ),
	token( "deck building" ),
	token( "collecting" ),
	token( "team building" ),
	token( "ressource management" ),
	token( "space management" ),
	token( "time manegement" ),
	token( "stats" ),
	token( "AI interactions", "an" ),
	token( "minigame" ),
	token( "stealth" ),
	token( "hidden objects" ),
	token( "idle" ),
	token( "programming" ),
	token( "rythm" ),
	token( "Non-linear progression" ),
	token( "Power-up based progression" )
];