
let setting = [
	token( "established", "an" ),
	token( "historical", "an" ),
	token( "modern" ),
	token( "fantasy" ),
	token( "science-fiction" ),
	token( "space" ),
	token( "alternate history", "an" ),
	token( "retro" ),
	token( "retro-futurist" ),
	token( "apocalyptic", "an" ),
	token( "post-apocalyptic" ),
	token( "post-post-apocalyptic" ),
	token( "war time" ),
	token( "near-future" ),
	token( "near-past" ),
	token( "cyberpunk" ),
	token( "mythologic" ),
	token( "classical antiquity" ),
	token( "virtual space" ),
];